import type { MarketplaceHomeResponse, MarketplaceHomeProduct } from "@/lib/marketplace-home.types";
import type { MarketplaceBrandsResponse } from "@/lib/marketplace-brands.types";
import type { MarketplaceStorefrontProductsResult } from "@/lib/marketplace-storefront.types";
import type { Tables } from "@/integrations/supabase/types";

/**
 * Visual fixtures gate: only allowed in development mode when explicitly enabled via env
 * (or fallback in dev when local backend is unreachable).
 * In production mode, fixtures are NEVER returned.
 */
export const isMarketplaceVisualFixturesEnabled = (): boolean => {
  if (typeof import.meta === "undefined" || !import.meta.env) return false;
  if (!import.meta.env.DEV) return false;
  return import.meta.env.VITE_MARKETPLACE_VISUAL_FIXTURES === "true" || import.meta.env.DEV;
};

export const FIXTURE_CATEGORIES: Tables<"categories">[] = [
  {
    id: "cat-1",
    name: "إلكترونيات وموبايل",
    slug: "electronics",
    image_url: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&q=80&auto=format&fit=crop",
    parent_id: null,
    is_active: true,
    is_featured: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    name: "أزياء وموضة",
    slug: "fashion",
    image_url: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=400&q=80&auto=format&fit=crop",
    parent_id: null,
    is_active: true,
    is_featured: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    name: "العناية والجمال",
    slug: "beauty",
    image_url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&q=80&auto=format&fit=crop",
    parent_id: null,
    is_active: true,
    is_featured: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-4",
    name: "المنزل والمطبخ",
    slug: "home",
    image_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&q=80&auto=format&fit=crop",
    parent_id: null,
    is_active: true,
    is_featured: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-5",
    name: "ساعات وإكسسوارات",
    slug: "watches",
    image_url: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=400&q=80&auto=format&fit=crop",
    parent_id: null,
    is_active: true,
    is_featured: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-6",
    name: "ألعاب وترفيه",
    slug: "gaming",
    image_url: "https://images.unsplash.com/photo-1612287233207-67c4e5183db2?w=400&q=80&auto=format&fit=crop",
    parent_id: null,
    is_active: true,
    is_featured: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-7",
    name: "رياضة ولياقة",
    slug: "sports",
    image_url: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400&q=80&auto=format&fit=crop",
    parent_id: null,
    is_active: true,
    is_featured: true,
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-8",
    name: "عطور شرقية وغربية",
    slug: "perfumes",
    image_url: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400&q=80&auto=format&fit=crop",
    parent_id: null,
    is_active: true,
    is_featured: true,
    sort_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const FIXTURE_OFFER_PRODUCTS: MarketplaceHomeProduct[] = [
  {
    id: "offer-1",
    name: "سماعات رأس لاسلكية احترافية عازلة للضوضاء",
    price: 55000,
    discount_price: 38000,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80&auto=format&fit=crop"],
    slug: "wireless-headphones-pro",
    stock: 25,
    is_active: true,
    is_best_seller: false,
    is_new: false,
    merchants: { id: "m1", slug: "dilmart-official", display_name: "متجر ديلمارت الرسمي", business_name: "متجر ديلمارت الرسمي" },
    offer_ends_at: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: "offer-2",
    name: "ساعة ذكية رياضية مع شاشة AMOLED وبطارية تدوم 7 أيام",
    price: 68000,
    discount_price: 49000,
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80&auto=format&fit=crop"],
    slug: "amoled-smart-watch",
    stock: 18,
    is_active: true,
    is_best_seller: true,
    is_new: false,
    merchants: { id: "m2", slug: "electronics-world", display_name: "عالم الإلكترونيات", business_name: "عالم الإلكترونيات" },
    offer_ends_at: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: "offer-3",
    name: "مكواة بخار عمودية احترافية سريعة التسخين للملابس",
    price: 48000,
    discount_price: 34000,
    images: ["https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&q=80&auto=format&fit=crop"],
    slug: "vertical-garment-steamer",
    stock: 12,
    is_active: true,
    is_best_seller: false,
    is_new: false,
    merchants: { id: "m3", slug: "modern-home", display_name: "البيت الحديث", business_name: "البيت الحديث" },
    offer_ends_at: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: "offer-4",
    name: "ماكينة حلاقة وتشذيب رجالية متعددة الرؤوس مع شحن سريع",
    price: 38000,
    discount_price: 25000,
    images: ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=600&q=80&auto=format&fit=crop"],
    slug: "mens-grooming-kit-pro",
    stock: 30,
    is_active: true,
    is_best_seller: true,
    is_new: false,
    merchants: { id: "m1", slug: "dilmart-official", display_name: "متجر ديلمارت الرسمي", business_name: "متجر ديلمارت الرسمي" },
    offer_ends_at: new Date(Date.now() + 86400000).toISOString(),
  },
];

export const FIXTURE_BEST_SELLERS: MarketplaceHomeProduct[] = [
  {
    id: "best-1",
    name: "مكبر صوت بلوتوث محمول مقاوم للماء مع صوت نقي",
    price: 29000,
    discount_price: null,
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80&auto=format&fit=crop"],
    slug: "portable-bluetooth-speaker",
    stock: 40,
    is_active: true,
    is_best_seller: true,
    is_new: false,
    merchants: { id: "m2", slug: "electronics-world", display_name: "عالم الإلكترونيات", business_name: "عالم الإلكترونيات" },
  },
  {
    id: "best-2",
    name: "طقم أواني طهي جرانيت غير لاصق 9 قطع فاخر",
    price: 85000,
    discount_price: 69000,
    images: ["https://images.unsplash.com/photo-1584990347449-397a61d15c7e?w=600&q=80&auto=format&fit=crop"],
    slug: "granite-cookware-set",
    stock: 15,
    is_active: true,
    is_best_seller: true,
    is_new: false,
    merchants: { id: "m3", slug: "modern-home", display_name: "البيت الحديث", business_name: "البيت الحديث" },
  },
  {
    id: "best-3",
    name: "عطر رجالي كلاسيكي شرقي فاخر 100 مل ثابت وفواح",
    price: 42000,
    discount_price: null,
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&q=80&auto=format&fit=crop"],
    slug: "classic-oriental-perfume",
    stock: 22,
    is_active: true,
    is_best_seller: true,
    is_new: false,
    merchants: { id: "m1", slug: "dilmart-official", display_name: "متجر ديلمارت الرسمي", business_name: "متجر ديلمارت الرسمي" },
  },
  {
    id: "best-4",
    name: "حقيبة ظهر عصرية مقاومة للماء مع منفذ شحن USB",
    price: 24000,
    discount_price: 19000,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80&auto=format&fit=crop"],
    slug: "waterproof-laptop-backpack",
    stock: 35,
    is_active: true,
    is_best_seller: true,
    is_new: false,
    merchants: { id: "m1", slug: "dilmart-official", display_name: "متجر ديلمارت الرسمي", business_name: "متجر ديلمارت الرسمي" },
  },
];

export const FIXTURE_NEW_ARRIVALS: MarketplaceHomeProduct[] = [
  {
    id: "new-1",
    name: "حامل هاتف ذكي للسيارة مع شاحن لاسلكي سريع 15 واط",
    price: 18000,
    discount_price: null,
    images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&q=80&auto=format&fit=crop"],
    slug: "wireless-car-charger-mount",
    stock: 50,
    is_active: true,
    is_best_seller: false,
    is_new: true,
    merchants: { id: "m2", slug: "electronics-world", display_name: "عالم الإلكترونيات", business_name: "عالم الإلكترونيات" },
  },
  {
    id: "new-2",
    name: "قلاية هوائية رقمية بدون زيت سعة 6 لتر موفرة للطاقة",
    price: 65000,
    discount_price: 54000,
    images: ["https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=600&q=80&auto=format&fit=crop"],
    slug: "digital-air-fryer-6l",
    stock: 14,
    is_active: true,
    is_best_seller: false,
    is_new: true,
    merchants: { id: "m3", slug: "modern-home", display_name: "البيت الحديث", business_name: "البيت الحديث" },
  },
  {
    id: "new-3",
    name: "نظارة شمسية أنيقة للرجال والنساء بحماية UV400",
    price: 16000,
    discount_price: null,
    images: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80&auto=format&fit=crop"],
    slug: "classic-uv400-sunglasses",
    stock: 45,
    is_active: true,
    is_best_seller: false,
    is_new: true,
    merchants: { id: "m1", slug: "dilmart-official", display_name: "متجر ديلمارت الرسمي", business_name: "متجر ديلمارت الرسمي" },
  },
  {
    id: "new-4",
    name: "لوحة مفاتيح ميكانيكية بإضاءة RGB مخصصة للألعاب",
    price: 36000,
    discount_price: 29000,
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80&auto=format&fit=crop"],
    slug: "rgb-mechanical-gaming-keyboard",
    stock: 20,
    is_active: true,
    is_best_seller: false,
    is_new: true,
    merchants: { id: "m2", slug: "electronics-world", display_name: "عالم الإلكترونيات", business_name: "عالم الإلكترونيات" },
  },
];

export const FIXTURE_MERCHANTS = [
  {
    id: "m1",
    slug: "dilmart-official",
    display_name: "متجر ديلمارت الرسمي",
    logo_url: "/logo/dilmart-store-icon-only2.png",
    description: "المتجر الرسمي لمنتجات ديلمارت المختارة بعناية",
    is_featured: true,
    status: "active",
  },
  {
    id: "m2",
    slug: "electronics-world",
    display_name: "عالم الإلكترونيات",
    logo_url: null,
    description: "أحدث الأجهزة والإلكترونيات ومستلزمات الهواتف",
    is_featured: true,
    status: "active",
  },
  {
    id: "m3",
    slug: "modern-home",
    display_name: "البيت الحديث",
    logo_url: null,
    description: "أفضل مستلزمات المنزل والأجهزة والمطابخ العصرية",
    is_featured: true,
    status: "active",
  },
];

export const FIXTURE_BRANDS: MarketplaceBrandsResponse = {
  brands: [
    { name: "Samsung", count: 48, imageUrl: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=200&q=80&auto=format&fit=crop" },
    { name: "Apple", count: 62, imageUrl: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=200&q=80&auto=format&fit=crop" },
    { name: "Sony", count: 34, imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200&q=80&auto=format&fit=crop" },
    { name: "Philips", count: 29, imageUrl: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=200&q=80&auto=format&fit=crop" },
    { name: "Nike", count: 55, imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&q=80&auto=format&fit=crop" },
    { name: "Adidas", count: 41, imageUrl: "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=200&q=80&auto=format&fit=crop" },
    { name: "Xiaomi", count: 37, imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02560?w=200&q=80&auto=format&fit=crop" },
  ],
};

export const FIXTURE_HOME_RESPONSE: MarketplaceHomeResponse = {
  contractVersion: 1,
  categories: FIXTURE_CATEGORIES,
  featuredMerchants: FIXTURE_MERCHANTS,
  offerProducts: FIXTURE_OFFER_PRODUCTS,
  featuredProducts: FIXTURE_BEST_SELLERS,
  newProducts: FIXTURE_NEW_ARRIVALS,
};

export const FIXTURE_DISCOVERY_PRODUCTS: MarketplaceStorefrontProductsResult = {
  items: [
    ...FIXTURE_OFFER_PRODUCTS,
    ...FIXTURE_BEST_SELLERS,
    ...FIXTURE_NEW_ARRIVALS,
  ],
  total: 12,
  offset: 0,
  limit: 24,
};
