-- DilMart Store: كتالوج معدات حلاقة وصالونات (رجالي + نسائي)
-- يستبدل الأقسام بالكامل، ويحذف المنتجات غير المرتبطة بعناصر طلبات (order_items).
-- المنتجات المرتبطة بطلبات سابقة تُحدَّث محتوياً مع الإبقاء على نفس id (يُحفظ سجل الطلبات).

-- فك ارتباط المنتجات قبل حذف الأقسام
UPDATE public.products SET category_id = NULL;

UPDATE public.categories SET parent_id = NULL;
DELETE FROM public.categories;

-- أقسام رئيسية: حلاقة رجالية + تجهيزات صالونات نسائية
INSERT INTO public.categories (name, slug, image_url, sort_order, parent_id) VALUES
(
  'ماكينات حلاقة ومشابك كهربائية',
  'barber-clippers',
  'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=700&q=80&auto=format&fit=crop',
  1,
  NULL
),
(
  'مقصات وشفرات وموس احترافي',
  'shears-razors',
  'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=700&q=80&auto=format&fit=crop',
  2,
  NULL
),
(
  'عناية باللحية والشارب',
  'beard-mustache-care',
  'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=700&q=80&auto=format&fit=crop',
  3,
  NULL
),
(
  'تجهيزات صالون حلاقة رجالي',
  'men-barber-furniture',
  'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=700&q=80&auto=format&fit=crop',
  4,
  NULL
),
(
  'أدوات تصفيف — صالون نسائي',
  'women-salon-styling',
  'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=700&q=85&auto=format&fit=crop',
  5,
  NULL
),
(
  'تعقيم وقفازات ومناشف ولابس صحي',
  'sanitation-disposables',
  'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=700&q=85&auto=format&fit=crop',
  6,
  NULL
),
(
  'مجففات ومكاوي وفُرش احترافية',
  'hair-dryers-tools',
  'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=700&q=80&auto=format&fit=crop',
  7,
  NULL
),
(
  'صبغة ومستلزمات صالون للشعر',
  'pro-hair-color-care',
  'https://images.unsplash.com/photo-1596462502278-27bfdd403348?w=700&q=85&auto=format&fit=crop',
  8,
  NULL
),
(
  'ملحقات صالون — بخاخات وروب وعبوات',
  'salon-accessories',
  'https://images.unsplash.com/photo-1541643600914-78b084683601?w=700&q=85&auto=format&fit=crop',
  9,
  NULL
);

-- حذف المنتجات غير المستخدمة في طلبات (يُحافظ على الطلبات القديمة)
DELETE FROM public.products p
WHERE NOT EXISTS (
  SELECT 1 FROM public.order_items oi WHERE oi.product_id = p.id
);

-- منتجات مرتبطة بطلبات سابقة: تحديث المحتوى مع slug فريد
UPDATE public.products p
SET
  category_id = (SELECT id FROM public.categories WHERE slug = 'barber-clippers' LIMIT 1),
  name = 'ماكينة حلاقة احترافية — مرجع مخزون مرتبط بطلب سابق',
  slug = 'DilMart-barber-legacy-' || replace(p.id::text, '-', ''),
  description = 'هذا المنتج مرتبط بسجل طلبات قديم؛ تم تحديث بيانات العرض لكتالوج الحلاقة. اسم المنتج في فاتورة الطلب الأصلية يبقى كما هو في تفاصيل الطلب.',
  price = 195000,
  discount_price = 169000,
  images = ARRAY[
    'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80&auto=format&fit=crop'
  ]::text[],
  stock = GREATEST(COALESCE(p.stock, 0), 2),
  is_active = true,
  is_featured = false,
  is_new = false,
  is_best_seller = false,
  sort_order = 0,
  offer_ends_at = NULL,
  loyalty_points_enabled = true
WHERE EXISTS (SELECT 1 FROM public.order_items oi WHERE oi.product_id = p.id);

-- إدراج كتالوج جديد (28 منتجاً)
INSERT INTO public.products (
  category_id,
  name,
  slug,
  description,
  price,
  discount_price,
  images,
  stock,
  is_active,
  is_featured,
  is_new,
  is_best_seller,
  sort_order,
  offer_ends_at,
  sold_count,
  low_stock_threshold,
  loyalty_points_enabled
)
SELECT
  c.id,
  v.name,
  v.slug,
  v.description,
  v.price,
  v.discount_price,
  v.images,
  v.stock,
  true,
  v.is_featured,
  v.is_new,
  v.is_best_seller,
  v.sort_order,
  CASE WHEN v.has_countdown THEN (now() + interval '5 days') ELSE NULL END,
  v.sold_count,
  v.low_stock_threshold,
  v.loyalty_points_enabled
FROM (VALUES
  -- ماكينات
  (
    'barber-clippers',
    'DilMart-barber-clipper-pro-01',
    'ماكينة حلاقة احترافية لاسلكية',
    'شفرات دقيقة، بطارية طويلة، مناسبة للصالون والمنزل. تشغيل هادئ مع مشط قابل للتعديل.'::text,
    285000::numeric,
    249000::numeric,
    ARRAY['https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80&auto=format&fit=crop']::text[],
    18::int,
    true,
    true,
    true,
    1,
    true,
    120,
    4,
    true
  ),
  (
    'barber-clippers',
    'DilMart-barber-clipper-pro-02',
    'مشبك تنعيم احترافي',
    'للتحديد الدقيق للخطوط والرقبة. يعمل مع معظم الماكينات الاحترافية.'::text,
    85000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80&auto=format&fit=crop']::text[],
    40::int,
    false,
    true,
    false,
    2,
    false,
    80,
    5,
    true
  ),
  (
    'barber-clippers',
    'DilMart-barber-clipper-pro-03',
    'ماكينة حلاقة سلكية عزم عالٍ',
    'مناسبة للاستخدام المكثف في الصالون، تبريد محسّن أثناء التشغيل.'::text,
    195000::numeric,
    175000::numeric,
    ARRAY['https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800&q=80&auto=format&fit=crop']::text[],
    10::int,
    true,
    false,
    true,
    3,
    true,
    45,
    3,
    true
  ),
  -- مقصات
  (
    'shears-razors',
    'DilMart-shears-01',
    'مقص حلاقة ياباني 6.5 بوصة',
    'حدة طويلة الأمد، مقابض مريحة، مناسب لتقص أطراف الشعر والتفريغ.'::text,
    165000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&q=80&auto=format&fit=crop']::text[],
    15::int,
    true,
    true,
    false,
    4,
    false,
    60,
    5,
    true
  ),
  (
    'shears-razors',
    'DilMart-razor-classic-01',
    'شفرات حلاقة تقليدية — طقم عناية',
    'مقبض معدني متوازن، شفرات قابلة للاستبدال، مناسب للحلاقة الرطبة.'::text,
    72000::numeric,
    59000::numeric,
    ARRAY['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=80&auto=format&fit=crop']::text[],
    55::int,
    false,
    false,
    true,
    5,
    true,
    200,
    5,
    true
  ),
  (
    'shears-razors',
    'DilMart-shavette-01',
    'موس حلاقة قابل لإعادة التعبئة',
    'للتفاصيل الدقيقة والخطوط؛ يُنظَّف بسهولة بين العملاء.'::text,
    48000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=80&auto=format&fit=crop']::text[],
    32::int,
    false,
    true,
    false,
    6,
    false,
    90,
    5,
    true
  ),
  -- لحية
  (
    'beard-mustache-care',
    'DilMart-beard-oil-01',
    'زيت لحية طبيعي — لافندر وخشب الأرز',
    'يرطب البشرة والشعر، رائحة هادئة مناسبة للصالون.'::text,
    38000::numeric,
    32000::numeric,
    ARRAY['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=80&auto=format&fit=crop']::text[],
    70::int,
    true,
    true,
    true,
    7,
    true,
    310,
    5,
    true
  ),
  (
    'beard-mustache-care',
    'DilMart-beard-balm-01',
    'بلسم شارب ولحية — ثبات خفيف',
    'ملمس غير لزج، يساعد على ترتيب الشعر وتقليل الهيشان.'::text,
    42000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=80&auto=format&fit=crop']::text[],
    45::int,
    false,
    false,
    false,
    8,
    false,
    70,
    5,
    true
  ),
  (
    'beard-mustache-care',
    'DilMart-mustache-wax-01',
    'شمع شارب قوي الثبات',
    'للتصفيف الدرامي في الصالون؛ يُذاب بين اليدين بسهولة.'::text,
    29000::numeric,
    24000::numeric,
    ARRAY['https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80&auto=format&fit=crop']::text[],
    60::int,
    true,
    false,
    true,
    9,
    false,
    140,
    5,
    true
  ),
  -- صالون رجالي
  (
    'men-barber-furniture',
    'DilMart-barber-chair-01',
    'كرسي حلاقة هيدروليك — جلد فاخر',
    'ارتفاع قابل للتعديل، مسند رأس مريح، قاعدة ثقيلة للثبات.'::text,
    1850000::numeric,
    1590000::numeric,
    ARRAY['https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=80&auto=format&fit=crop']::text[],
    3::int,
    true,
    true,
    true,
    10,
    true,
    12,
    1,
    true
  ),
  (
    'men-barber-furniture',
    'DilMart-barber-station-01',
    'محطة عمل حلاق — رف أدوات ومرآة LED',
    'تنظيم مقصات ومواد، إضاءة محيطة للعمل الدقيق.'::text,
    920000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=80&auto=format&fit=crop']::text[],
    4::int,
    false,
    true,
    false,
    11,
    false,
    8,
    2,
    true
  ),
  -- صالون نسائي
  (
    'women-salon-styling',
    'DilMart-salon-curling-iron-01',
    'مكواة تجعيد سيراميك — صالون نسائي',
    'حرارة ثابتة، طلاء أيوني يقلل الهيشان؛ مناسبة للتسريحات اليومية والمناسبات.'::text,
    145000::numeric,
    125000::numeric,
    ARRAY['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800&q=80&auto=format&fit=crop']::text[],
    22::int,
    true,
    true,
    true,
    12,
    true,
    210,
    4,
    true
  ),
  (
    'women-salon-styling',
    'DilMart-salon-hot-brush-01',
    'فرشاة حرارية دوارة',
    'لنعومة ولمعان؛ خفيفة الوزن لاستخدام طويل في الصالون النسائي.'::text,
    118000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800&q=85&auto=format&fit=crop']::text[],
    16::int,
    false,
    true,
    false,
    13,
    false,
    95,
    5,
    true
  ),
  (
    'women-salon-styling',
    'DilMart-salon-section-clips-01',
    'مشابك تثبيت تسريحات — طقم صالون',
    'مقاومة للحرارة، تمسك قوي دون كسر الشعر.'::text,
    35000::numeric,
    28000::numeric,
    ARRAY['https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=85&auto=format&fit=crop']::text[],
    80::int,
    true,
    false,
    true,
    14,
    true,
    400,
    5,
    true
  ),
  (
    'women-salon-styling',
    'DilMart-salon-blowout-brush-01',
    'فرشاة مجفف بيضاوية احترافية',
    'لمسات نهائية ناعمة؛ مقبض مريح للاستخدام المطوّل.'::text,
    78000::numeric,
    65000::numeric,
    ARRAY['https://images.unsplash.com/photo-1596462502278-27bfdd403348?w=800&q=85&auto=format&fit=crop']::text[],
    28::int,
    false,
    true,
    false,
    15,
    false,
    150,
    5,
    true
  ),
  -- تعقيم
  (
    'sanitation-disposables',
    'DilMart-gloves-nitrile-01',
    'قفازات نتريل — صندوق صالون',
    'بدون بودرة، مقاس L، مناسبة للتعامل مع المواد الكيميائية.'::text,
    45000::numeric,
    38000::numeric,
    ARRAY['https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=85&auto=format&fit=crop']::text[],
    100::int,
    true,
    false,
    true,
    16,
    true,
    520,
    10,
    true
  ),
  (
    'sanitation-disposables',
    'DilMart-disinfectant-spray-01',
    'رذاذ تعقيم أسطح وأدوات',
    'تركيبة سريعة الجفاف، مناسبة بين العملاء في الصالون.'::text,
    28000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=85&auto=format&fit=crop']::text[],
    65::int,
    false,
    true,
    false,
    17,
    false,
    180,
    5,
    true
  ),
  (
    'sanitation-disposables',
    'DilMart-barber-towels-01',
    'مناشف صالون قطنية — عبوة',
    'سريعة الامتصاص، قابلة للغسل المتكرر.'::text,
    52000::numeric,
    44000::numeric,
    ARRAY['https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&q=85&auto=format&fit=crop']::text[],
    40::int,
    true,
    false,
    false,
    18,
    false,
    110,
    5,
    true
  ),
  -- مجففات
  (
    'hair-dryers-tools',
    'DilMart-pro-dryer-01',
    'مجفف شعر احترافي 2200 واط',
    'أيوني، سرعات متعددة، مناسب للصالون.'::text,
    265000::numeric,
    229000::numeric,
    ARRAY['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800&q=80&auto=format&fit=crop']::text[],
    14::int,
    true,
    true,
    true,
    19,
    true,
    175,
    3,
    true
  ),
  (
    'hair-dryers-tools',
    'DilMart-paddle-brush-01',
    'فرشاة مسطحة احترافية للفك',
    'أسنان مرنة، تقلل الكسر أثناء التجفيف.'::text,
    32000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800&q=80&auto=format&fit=crop']::text[],
    50::int,
    false,
    false,
    true,
    20,
    false,
    88,
    5,
    true
  ),
  (
    'hair-dryers-tools',
    'DilMart-round-brush-01',
    'فرشاة أسطوانية للتجعيد بالمجفف',
    'قطر 43مم، مناسبة لشعر متوسط الطول.'::text,
    38000::numeric,
    31000::numeric,
    ARRAY['https://images.unsplash.com/photo-1596462502278-27bfdd403348?w=800&q=80&auto=format&fit=crop']::text[],
    36::int,
    true,
    true,
    false,
    21,
    false,
    130,
    5,
    true
  ),
  -- صبغة
  (
    'pro-hair-color-care',
    'DilMart-color-bowl-01',
    'طقم أوعية صبغة مع فرشاة',
    'بلاستيك مقاوم للمواد الكيميائية، سهل التنظيف.'::text,
    22000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1596462502278-27bfdd403348?w=800&q=85&auto=format&fit=crop']::text[],
    90::int,
    false,
    true,
    false,
    22,
    false,
    240,
    5,
    true
  ),
  (
    'pro-hair-color-care',
    'DilMart-foil-roll-01',
    'رقائق ألمنيوم للصبغة — لفافة صالون',
    'عرض مناسب لتغطية الخصل بسرعة.'::text,
    18000::numeric,
    15000::numeric,
    ARRAY['https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=85&auto=format&fit=crop']::text[],
    120::int,
    true,
    false,
    true,
    23,
    true,
    330,
    5,
    true
  ),
  (
    'pro-hair-color-care',
    'DilMart-color-brush-01',
    'فرشاة صبغة عريضة',
    'شعيرات متساوية لتوزيع متجانس.'::text,
    12000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1596462502278-27bfdd403348?w=800&q=80&auto=format&fit=crop']::text[],
    200::int,
    false,
    false,
    false,
    24,
    false,
    400,
    5,
    true
  ),
  -- ملحقات
  (
    'salon-accessories',
    'DilMart-spray-bottle-01',
    'بخاخات رذاذ — طقم صالون',
    'للماء أو المحاليل الخفيفة؛ رشّة ناعمة.'::text,
    15000::numeric,
    12000::numeric,
    ARRAY['https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=85&auto=format&fit=crop']::text[],
    150::int,
    true,
    false,
    true,
    25,
    false,
    500,
    5,
    true
  ),
  (
    'salon-accessories',
    'DilMart-barber-cape-01',
    'روب حلاقة مقاوم للماء',
    'إغلاق سحّاب، خفيف على العميل.'::text,
    48000::numeric,
    NULL::numeric,
    ARRAY['https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=80&auto=format&fit=crop']::text[],
    35::int,
    false,
    true,
    false,
    26,
    false,
    75,
    5,
    true
  ),
  (
    'salon-accessories',
    'DilMart-neck-duster-01',
    'فرشاة إزالة الشعر الرقيق',
    'شعيرات ناعمة للرقبة والأذن بعد الحلاقة.'::text,
    18000::numeric,
    14000::numeric,
    ARRAY['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=80&auto=format&fit=crop']::text[],
    85::int,
    true,
    true,
    false,
    27,
    true,
    260,
    5,
    true
  ),
  -- عينات مخزون منخفض / عرض
  (
    'barber-clippers',
    'DilMart-barber-oos-sample',
    'عينة نفاد مخزون (عرض واجهة)',
    'منتج تجريبي لاختبار حالة «غير متوفر» في المتجر.'::text,
    55000::numeric,
    39000::numeric,
    ARRAY['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80&auto=format&fit=crop']::text[],
    0::int,
    true,
    false,
    false,
    28,
    false,
    0,
    5,
    true
  )
) AS v(
  cat_slug,
  slug,
  name,
  description,
  price,
  discount_price,
  images,
  stock,
  is_featured,
  is_new,
  is_best_seller,
  sort_order,
  has_countdown,
  sold_count,
  low_stock_threshold,
  loyalty_points_enabled
)
JOIN public.categories c ON c.slug = v.cat_slug;
