#!/usr/bin/env node
/**
 * Bulk catalog import CLI — inventory / prepare / dry-run / preflight / execute / resume / postflight.
 *
 * preflight is production read-only. execute/resume require a separate, later
 * BULK2200 execution authorization and remain fail-closed by default.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { loadConfig } from "./lib/config.mjs";
import { writeCsv, writeJson, sha256File } from "./lib/csv.mjs";
import { runInventory, prepareBatch, buildDryRunReport } from "./lib/pipeline.mjs";
import { assertBulkExecuteAuthorized } from "./lib/constants.mjs";
import {
  runExecute,
  runPostflight,
  runPreflight,
  runResume,
  writePreflightEvidence,
} from "./lib/runtime.mjs";
import {
  createFakeRuntimeAdapters,
  createProductionRuntimeAdapters,
  resolveBulkRuntimeEnv,
} from "./lib/runtime-adapters.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

function usage() {
  return `Usage:
  node scripts/product-import/bulk-catalog/run.mjs inventory --config <file>
  node scripts/product-import/bulk-catalog/run.mjs prepare --config <file> [--batch <id>]
  node scripts/product-import/bulk-catalog/run.mjs dry-run --config <file> --batch <id>
  node scripts/product-import/bulk-catalog/run.mjs preflight --config <file> --batch <id>
  node scripts/product-import/bulk-catalog/run.mjs execute --config <file> --batch <id>
  node scripts/product-import/bulk-catalog/run.mjs resume --config <file> --batch <id>
  node scripts/product-import/bulk-catalog/run.mjs postflight --config <file> --batch <id>
`;
}

function parseArgs(argv) {
  const out = { cmd: null, config: null, batch: null };
  out.cmd = argv[0] || null;
  for (let i = 1; i < argv.length; i++) {
    if (argv[i] === "--config") out.config = argv[++i];
    else if (argv[i] === "--batch") out.batch = argv[++i];
  }
  return out;
}

function fail(obj, code = 1) {
  console.error(JSON.stringify({ ok: false, ...obj }, null, 2));
  process.exit(code);
}

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  for (const line of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (!match || process.env[match[1]]) continue;
    let value = match[2].trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    process.env[match[1]] = value;
  }
}

function printableRuntimeReport(report) {
  const out = { ...report };
  delete out.resolved;
  delete out.existing_baselines;
  return out;
}

function buildRuntimeAdapters(command) {
  const fakePath = process.env.BULK2200_FAKE_ADAPTERS_JSON;
  if (fakePath) {
    const allowed = process.env.NODE_ENV === "test" && process.env.BULK2200_TEST_MODE === "1";
    if (!allowed) throw new Error(`FAKE_ADAPTERS_FORBIDDEN:${command}`);
    return createFakeRuntimeAdapters(JSON.parse(fs.readFileSync(fakePath, "utf8")));
  }
  loadEnvFile(path.join(ROOT, "backend/.env"));
  loadEnvFile(path.join(ROOT, ".env"));
  const env = resolveBulkRuntimeEnv(process.env);
  if (!env.key.ok) throw new Error(env.key.code || "UNSUPPORTED_SERVER_KEY");
  if (!env.adminJwt) throw new Error("ADMIN_JWT_INVALID");
  return createProductionRuntimeAdapters({
    supabaseUrl: env.supabaseUrl,
    serverKey: env.key.key,
    serverKeySource: env.key.source,
    adminJwt: env.adminJwt,
    backendApi: env.backendApi,
    readOnly: command === "preflight" || command === "postflight",
  });
}

function inventoryMarkdown(report, { root }) {
  const rel = (p) => {
    if (!p) return "(n/a)";
    const a = String(p).replace(/\\/g, "/");
    const r = String(root).replace(/\\/g, "/");
    if (a.toLowerCase().startsWith(r.toLowerCase() + "/")) return a.slice(r.length + 1);
    return p;
  };
  return `# Bulk2200 Source Inventory

Generated by \`bulk-catalog/run.mjs inventory\` (read-only).

## Primary source

| Item | Value |
|---|---|
| Source CSV | \`${rel(report.source_file)}\` |
| Source workbook (outside git) | \`${rel(report.source_workbook)}\` |
| Source CSV SHA-256 | \`${report.source_file_sha256}\` |
| Workbook SHA-256 (documented) | \`44064E6B38FED755A9A860111AFFD200C1A59B1A88877980C662C970C2B3A239\` |

## Counts

| Metric | Value |
|---|---|
| Total source rows | ${report.total_source_rows} |
| Unique SKUs | ${report.total_unique_skus} |
| Duplicate SKUs | ${report.duplicate_skus} |
| Rows without SKU | ${report.rows_without_sku} |
| Rows without name | ${report.rows_without_name} |
| Rows without category | ${report.rows_without_category} |
| Rows without local image | ${report.rows_without_image} |
| Rows with multiple images | ${report.rows_with_multiple_images} |
| Rows with price | ${report.rows_with_price} |
| Rows with stock | ${report.rows_with_stock} |
| Image files found | ${report.image_files_found} |
| Orphan images | ${report.orphan_images} |
| Missing image references | ${report.missing_image_references} |
| Categories resolved | ${report.categories_resolved} |
| Categories unresolved | ${report.categories_unresolved} |
| Existing catalog SKU collisions | ${report.source_sku_collisions} |

## Unsupported / unknown fields

${
  report.unsupported_or_unknown_fields.length
    ? report.unsupported_or_unknown_fields.map((f) => `- \`${f}\``).join("\n")
    : "_None_"
}

## Notes

- Do not assume the corpus is exactly 2200 — this inventory measured **${report.total_source_rows}** source rows.
- Full-catalog local images are not present; Batch001 READY size is gated by usable local images after SKU collision filters.
- Production Storage/DB writes: **NO** / **NO**
`;
}

async function main(argv = process.argv.slice(2)) {
  const args = parseArgs(argv);
  if (!args.cmd || !args.config) {
    fail({ error: "ARGS_REQUIRED", usage: usage() }, 2);
  }
  const cfg = loadConfig(args.config, { root: ROOT });
  const batchId = args.batch || cfg.batch_id || "batch001";

  if (args.cmd === "inventory") {
    const { report } = runInventory(cfg);
    const rel = (p) => {
      if (!p) return null;
      const a = String(p).replace(/\\/g, "/");
      const r = String(ROOT).replace(/\\/g, "/");
      if (a.toLowerCase().startsWith(r.toLowerCase() + "/")) return a.slice(r.length + 1);
      return p;
    };
    const safeReport = {
      ...report,
      source_file: rel(report.source_file),
      source_workbook: rel(report.source_workbook),
    };
    const outJson = path.join(cfg.docs_dir, "00_SOURCE_INVENTORY.json");
    const outMd = path.join(cfg.docs_dir, "00_SOURCE_INVENTORY.md");
    writeJson(outJson, safeReport);
    fs.mkdirSync(cfg.docs_dir, { recursive: true });
    fs.writeFileSync(outMd, inventoryMarkdown(safeReport, { root: ROOT }), "utf8");
    console.log(JSON.stringify({ ok: true, command: "inventory", report: safeReport, docs: { json: outJson, md: outMd } }, null, 2));
    return;
  }

  if (args.cmd === "prepare" || args.cmd === "dry-run") {
    const prepared = prepareBatch(cfg, { batchId, root: ROOT });
    const batchDir = path.join(cfg.docs_dir, batchId);
    fs.mkdirSync(batchDir, { recursive: true });
    const manifestPath = path.join(batchDir, `01_${batchId.toUpperCase()}_MANIFEST.csv`);
    const headers = [
      "batch_id",
      "source_row_number",
      "merchant_sku",
      "normalized_name",
      "slug",
      "category",
      "brand",
      "size",
      "price_source_status",
      "image_readiness_status",
      "image_source",
      "normalized_image_path",
      "image_sha256",
      "validation_status",
      "rejection_reason",
    ];
    writeCsv(manifestPath, headers, prepared.manifestRows);
    const manifestSha = sha256File(manifestPath);

    const dry = buildDryRunReport(cfg, prepared);
    dry.manifest_path = path.relative(ROOT, manifestPath).replace(/\\/g, "/");
    dry.manifest_sha256 = manifestSha;
    dry.corpus_status_counts = prepared.counts;
    dry.ready_in_corpus = prepared.counts.READY;
    dry.batch_ready_capped = prepared.selectedReady.length;

    const dryPath = path.join(batchDir, `02_${batchId.toUpperCase()}_DRY_RUN.json`);
    writeJson(dryPath, dry);

    const auditFile = path.join(batchDir, "06_IDENTITY_AUDIT.json");
    const auditList = fs.existsSync(auditFile) ? JSON.parse(fs.readFileSync(auditFile, "utf8")) : [];
    const exactMatches = (Array.isArray(auditList) ? auditList : []).filter((a) => a.identity_decision === "EXACT_MATCH").length;
    const holdsSelected = (Array.isArray(auditList) ? auditList : []).filter((a) => a.identity_decision === "HOLD_REVIEW").length;

    const identityGatePass =
      dry.would_create >= Math.min(200, cfg.batch_size) &&
      dry.zero_writes_performed &&
      auditList.length >= 200 &&
      holdsSelected === 0;

    const readiness = `# ${batchId.toUpperCase()} Readiness

## Binding

| Item | Value |
|---|---|
| Batch ID | \`${batchId}\` |
| Merchant | \`${cfg.merchant_id}\` (\`${cfg.merchant_slug}\`) |
| Manifest SHA-256 | \`${manifestSha}\` |
| Batch size cap | ${cfg.batch_size} |
| Selection rule | \`${cfg.batch_selection_rule}\` |

## Dry-run

| Metric | Value |
|---|---|
| Selected READY (capped) | **${dry.selected_rows}** |
| Would create | **${dry.would_create}** |
| Existing SKU skips (corpus) | ${dry.existing_sku_skips} |
| Invalid rejects (corpus) | ${dry.invalid_rejects} |
| Duplicate rejects | ${dry.duplicate_rejects} |
| Category failures | ${dry.category_mapping_failures} |
| Missing image failures | ${dry.missing_image_failures} |
| HOLD_REVIEW | ${dry.hold_review} |
| Identity Audit Rows | ${auditList.length} |
| Exact Identity Matches | ${exactMatches} |
| Identity Holds Selected | ${holdsSelected} |
| Expected Storage uploads | ${dry.expected_storage_object_count} |
| Expected DB inserts | ${dry.expected_db_insert_count} |
| Production writes | **NO / NO** |

## Defaults

Every create would use: private / inactive / unpublished / stock = 0.

## Judgment

${
  identityGatePass
    ? `**${batchId.toUpperCase()}_STAGING_READY_FOR_EXECUTION_REVIEW**`
    : `**NO-GO** - identity gates failed or holds selected in manifest (holdsSelected=${holdsSelected}).`
}
`;
    const readyPath = path.join(batchDir, `03_${batchId.toUpperCase()}_READINESS.md`);
    fs.writeFileSync(readyPath, readiness, "utf8");

    // Persist classified summary for tmp (not docs)
    writeJson(path.join(cfg.tmp_dir, batchId, "classified-summary.json"), {
      counts: prepared.counts,
      selected: prepared.selectedReady.map((r) => r.merchant_sku),
      manifest_sha256: manifestSha,
    });

    console.log(
      JSON.stringify(
        {
          ok: true,
          command: args.cmd,
          batch_id: batchId,
          manifest_sha256: manifestSha,
          dry_run: dry,
          paths: { manifestPath, dryPath, readyPath },
          production_storage_writes: false,
          production_db_writes: false,
        },
        null,
        2,
      ),
    );
    return;
  }

  if (args.cmd === "preflight") {
    const adapters = buildRuntimeAdapters("preflight");
    const report = await runPreflight({ cfg, batchId, root: ROOT, adapters, env: process.env });
    const evidence = writePreflightEvidence(report, { cfg, batchId });
    const output = {
      ...printableRuntimeReport(report),
      evidence_path: evidence.path,
      evidence_sha256: evidence.sha256,
    };
    console.log(JSON.stringify(output, null, 2));
    if (!report.ok) process.exitCode = 1;
    return;
  }

  if (args.cmd === "execute" || args.cmd === "resume") {
    const gate = assertBulkExecuteAuthorized(process.env);
    if (!gate.ok) {
      fail({
        command: args.cmd,
        error: gate.code,
        message: gate.message,
        production_storage_writes: false,
        production_db_writes: false,
      });
    }
    const adapters = buildRuntimeAdapters(args.cmd);
    const report =
      args.cmd === "execute"
        ? await runExecute({ cfg, batchId, root: ROOT, adapters, env: process.env })
        : await runResume({ cfg, batchId, root: ROOT, adapters, env: process.env });
    const output = printableRuntimeReport(report);
    if (!report.ok) fail({ command: args.cmd, ...output });
    console.log(JSON.stringify({ command: args.cmd, ...output }, null, 2));
    return;
  }

  if (args.cmd === "postflight") {
    const adapters = buildRuntimeAdapters("postflight");
    const report = await runPostflight({ cfg, batchId, root: ROOT, adapters, env: process.env });
    if (!report.ok) fail({ command: "postflight", ...report });
    console.log(JSON.stringify({ command: "postflight", ...report }, null, 2));
    return;
  }

  fail({ error: "UNKNOWN_COMMAND", command: args.cmd, usage: usage() }, 2);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch((e) => fail({ error: "UNCAUGHT", message: String(e?.message || e) }));
}

export { buildRuntimeAdapters, main, parseArgs };
